DROP TABLE IF EXISTS EntryFeelings CASCADE;
DROP TABLE IF EXISTS ActivityFeelings CASCADE;
DROP TABLE IF EXISTS Entries CASCADE;
DROP TABLE IF EXISTS Feelings CASCADE;
DROP TABLE IF EXISTS Activities CASCADE;
DROP TABLE IF EXISTS Weeks CASCADE;
